### ISSUE TITLE
Plugin is discovered on every run

### ISSUE THREAD

**Issue by arznaar** [christianjunk/cordova-plugin-itunesfilesharing#2]
Every time you hit "cordova run android" cli spend some time saying:
> Discovered plugin "cordova-plugin-itunesfilesharing" in config.xml. Adding it to the project

Now, due to changes in cordova 7.0 it takes more than 20 seconds (it ignores the fact that plugin is already installed)

This problem is caused by using 'id="io.phasr.cordova.plugin.itunesfilesharing"' in plugin.xml and "cordova"."id": "io.phasr.cordova.plugin.itunesfilesharing" in package.json

Please change it to "cordova-plugin-itunesfilesharing"

**Comment by u01jmg3** [comment]
A PR might move this along

**Comment by ddvornik** [comment]
please update npm package

**Comment by christianjunk** [comment]
@ddvornik Update (v0.0.2) available here: https://www.npmjs.com/package/cordova-plugin-itunesfilesharing

**Comment by ddvornik** [comment]
@christianjunk thank you
